### ISSUE TITLE
The display of the images does not work anymore

### ISSUE THREAD

**Issue by Iratep** [StarburstAudio/loopbase#60]
Since few days, The display of the images does not work anymore: 
![2022-05-07 21_32_00-Loopbase](https://user-images.githubusercontent.com/105127883/167269150-07c91927-4d85-4524-9a33-763eb66b261e.png)

**Comment by stxarixdust** [comment]
Something on Looperman's back-end must've changed - They now have this `?d` parameter after every image that seems to be linked to user sessions. As of right now, every Axios request performed seems to start a new session. This is why the `?d` parameter in the image URLs is different for every request.

![Screenshot_20220519_113620](https://user-images.githubusercontent.com/68156346/169263386-7c205d40-a675-4b60-a455-74df88f5a5be.png)

We'll probably have to find a way to retain one session across all requests and then send the images as base64 to the front-end. I'm looking into a fix for this right now.

**Comment by stxarixdust** [comment]
The `?d` parameter is unrelated, it's presumably for timestamps. The real issue was the site looking for Looperman as the referrer in the GET headers. With commit https://github.com/StarburstAudio/loopbase/commit/1c8325d795e6d06700678b4f2fc62b1a898276b9, I managed to resolve this issue. Does it work on your end now, too?

**Comment by Iratep** [comment]
Hi,

It works on my side, thanks for solving quickly this issue :)
